# Generated by Django 4.0.1 on 2022-04-19 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurentRegModel',
            fields=[
                ('restaurent_id', models.AutoField(primary_key=True, serialize=False)),
                ('restaurent_name', models.CharField(max_length=100)),
                ('restaurent_email', models.EmailField(max_length=100)),
                ('restaurent_mobile', models.BigIntegerField()),
                ('restaurent_address', models.CharField(max_length=100)),
                ('restaurent_logo', models.ImageField(upload_to='images/')),
                ('restaurent_license', models.ImageField(upload_to='images/')),
                ('restaurent_password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurentMenuModel',
            fields=[
                ('menu_id', models.AutoField(primary_key=True, serialize=False)),
                ('menu_food_type', models.CharField(max_length=100)),
                ('menu_category', models.CharField(max_length=100)),
                ('menu_name', models.CharField(max_length=100)),
                ('menu_price', models.CharField(max_length=100)),
                ('menu_quantity', models.CharField(max_length=100)),
                ('menu_details', models.CharField(max_length=100)),
                ('menu_image', models.ImageField(upload_to='images/')),
                ('restaurent', models.ForeignKey(db_column='restaurent', on_delete=django.db.models.deletion.CASCADE, related_name='restaurent', to='restaurentapp.restaurentregmodel')),
            ],
        ),
    ]
