# Generated by Django 4.0.3 on 2022-05-24 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurentRegModel',
            fields=[
                ('restaurent_id', models.AutoField(primary_key=True, serialize=False)),
                ('restaurent_name', models.CharField(max_length=100)),
                ('restaurent_email', models.EmailField(max_length=100)),
                ('restaurent_mobile', models.BigIntegerField()),
                ('restaurent_address', models.CharField(max_length=100)),
                ('restaurent_logo', models.ImageField(upload_to='images/')),
                ('restaurent_license', models.ImageField(upload_to='images/')),
                ('restaurent_password', models.CharField(max_length=100)),
                ('status', models.CharField(default='pending', max_length=100)),
            ],
            options={
                'db_table': 'restaurent_registration_details',
            },
        ),
        migrations.CreateModel(
            name='RestaurentTableModel',
            fields=[
                ('table_id', models.AutoField(primary_key=True, serialize=False)),
                ('table_type', models.CharField(max_length=100)),
                ('table_price', models.CharField(max_length=100)),
                ('table_details', models.CharField(max_length=100)),
                ('table_image', models.ImageField(upload_to='images/')),
                ('restaurent', models.ForeignKey(db_column='restaurent', on_delete=django.db.models.deletion.CASCADE, to='restaurentapp.restaurentregmodel')),
            ],
            options={
                'db_table': 'restaurent_table_details',
            },
        ),
    ]
