# Generated by Django 4.0.3 on 2022-04-20 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurentapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurentregmodel',
            name='status',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
