# Generated by Django 4.0.3 on 2022-05-26 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurentapp', '0003_alter_restaurenttablemodel_total_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurenttablemodel',
            name='table_members',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
