# Generated by Django 4.0.1 on 2022-05-07 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurentapp', '0003_alter_restaurentmenumodel_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurentTableodel',
            fields=[
                ('table_id', models.AutoField(primary_key=True, serialize=False)),
                ('table_type', models.CharField(max_length=100)),
                ('table_price', models.CharField(max_length=100)),
                ('table_details', models.CharField(max_length=100)),
                ('table_image', models.ImageField(upload_to='images/')),
                ('restaurent', models.ForeignKey(db_column='restaurent', on_delete=django.db.models.deletion.CASCADE, related_name='restaurent', to='restaurentapp.restaurentregmodel')),
            ],
            options={
                'db_table': 'restaurent_table_details',
            },
        ),
        migrations.DeleteModel(
            name='RestaurentMenuModel',
        ),
    ]
