# Generated by Django 4.0.1 on 2022-05-07 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegModel',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=100)),
                ('user_mobile', models.BigIntegerField()),
                ('user_password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'user_registration_details',
            },
        ),
    ]
