# Generated by Django 4.0.3 on 2022-05-24 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeedbackmodel',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
