# Generated by Django 4.0.3 on 2022-05-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_userfeedbackmodel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbooktablemodel',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
